name: examp4
description: "Sebuah Exam Browser"
publish_to: 'none'

version: 1.2.1+3

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # WebView
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.2

  # Lainnya
  http: ^1.2.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  upgrader: ^9.0.0 # Ganti ke upgrader

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
